sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "stable"

before_install:
  # if npm version is less than 3.0.0, upgrade to 3
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi

before_deploy:
  - npm install -g auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: Vfs9LIJtu0GGQqEk74aypqUGk0925/41ioOkAoHxWQwZGkhvZsVDJsfe2Two47uJGGoq17vScorrhiXFZXRvKpdwFl1uHyeIMPQj66DG1cksw972z3mtKMLrxmwSuRk9LNgnow5kUPZfoNuHl0u/9Fjp0ieicwYJMi0ojxUEZvM=
  on:
    tags: true
    repo: ember-cli/broccoli-lint-eslint
