language: node_js
node_js:
  - "6"
  - "8"
  - "10"

env:
  global:
    - FORCE_PERSISTENCE_IN_CI=true
  matrix:
    - NPM_SCRIPT=test

matrix:
  include:
    - node_js: "6"
      env: NPM_SCRIPT=lint

script:
  - npm run $NPM_SCRIPT

before_deploy:
  - npm install -g auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: Vfs9LIJtu0GGQqEk74aypqUGk0925/41ioOkAoHxWQwZGkhvZsVDJsfe2Two47uJGGoq17vScorrhiXFZXRvKpdwFl1uHyeIMPQj66DG1cksw972z3mtKMLrxmwSuRk9LNgnow5kUPZfoNuHl0u/9Fjp0ieicwYJMi0ojxUEZvM=
  on:
    tags: true
    repo: ember-cli/broccoli-lint-eslint
